### ISSUE TITLE
"Local Npm module "grunt-adb" not found"

### ISSUE THREAD

**Issue by innerdaze** [lesfrontaliers/grunt-adb#1]
Using your example, I'm getting the "Local Npm module "grunt-adb" not found. Is it installed?" error.

I have installed as a dev-dependency using --save-dev and I can see the module in my node_modules folder.

Not sure what the issue could be as this is the only grunt task that's causing this issue

**Comment by vincent** [comment]
not sure why it does not work with a symlink.
anyway, it should work now. I've also updated the npm package.

**Comment by innerdaze** [comment]
Now I'm getting this error after doing `npm install grunt-adb`

``` bash
npm ERR! Error: shasum check failed for /home/lee/tmp/npm-4780-04n7yd9X/1393698232119-0.19551198068074882/tmp.tgz
npm ERR! Expected: 74e3058a63f0fd80f1b7ecbbb14a69e3cdc96e22
npm ERR! Actual:   66433e4ec6a6f7176f12c4b9540082853bfe3e36
```

If I `wget` the tar directly, it works fine - so the symlinking has worked :)

**Comment by jarseneault** [comment]
I am also getting the error about the failed shasum.  Author probably needs to update it in npm.

**Comment by vincent** [comment]
I've just published a new version on npm, could you try now please ?

**Comment by jarseneault** [comment]
Works now, thanks.
